spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kis
    username: hyejin
    password: qwer1234!
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false

tago:
  service-key: ${tago-servicekey}
  city-code: 37050