spring:
  datasource:
    generate-unique-name: false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: alfud1004
    url: jdbc:mysql://localhost:3306/kis_db
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
