spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kis_db
    username: root
    password: alfud1004
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true